循环体里捕获异常，可以让循环继续执行
String[] s = {"1","2","3","4","5","1","2","3","4","5"};
for (int i = 0; i < s.length; i++) {
    try {
        if (i == 5) {
            throw new Exception(i + ":这里抛出异常！");
        }
        System.out.println(i + ":" + s[i]);
    }
    catch (Exception e){
        System.out.println(i + ":" + s[i]);
    }
}